name: Build Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Console:
    runs-on: windows-2016
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Console
        run: |
          "BUILD_INFO = 'Windows v"+${{ steps.tag.outputs.result }}+" (32-bit)'" | Out-File -FilePath BuildInfo.py -Encoding UTF8
      - name: Build
        working-directory: Console
        run: |
          nuitka --standalone --windows-icon-from-ico=Resources/Core/Logo.ico `
                 --windows-company-name=HCC --windows-uac-admin --windows-disable-console `
                 --windows-product-name="PYCM Console" --windows-product-version=${{ steps.tag.outputs.result }} `
                 --windows-file-description="PYCM Console" --windows-file-version=${{ steps.tag.outputs.result }} `
                 --include-data-file=Translation/*.qm=Translation/ `
                 --enable-plugin=pyqt5 --enable-plugin=multiprocessing `
                 --assume-yes-for-downloads --disable-ccache --remove-output `
                 --output-dir=Build ConsoleMain.py
      - name: Check build
        working-directory: Console
        run: |
          if(!(Test-Path Build/ConsoleMain.dist/ConsoleMain.exe)){ exit 1 }
          Rename-Item Build/ConsoleMain.dist Console
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: Console/Build/
          dest: PYCM-Console-Windows.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Console-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-Client:
    runs-on: windows-2016
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Client
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.result }}
        run: |
          "BUILD_INFO = 'Windows v"+${{ steps.tag.outputs.result }}+" (32-bit)'" | Out-File -FilePath BuildInfo.py -Encoding UTF8
      - name: Build
        working-directory: Client
        run: |
          nuitka --standalone --windows-icon-from-ico=Resources/Core/Logo.ico `
                 --windows-company-name=HCC --windows-uac-admin --windows-disable-console `
                 --windows-product-name="PYCM Client" --windows-product-version=${{ steps.tag.outputs.result }} `
                 --windows-file-description="PYCM Client" --windows-file-version=${{ steps.tag.outputs.result }} `
                 --include-data-file=Translation/*.qm=Translation/ `
                 --enable-plugin=pyqt5 `
                 --assume-yes-for-downloads --disable-ccache  --remove-output `
                 --output-dir=Build ClientMain.py
      - name: Check build
        working-directory: Client
        run: |
          if(!(Test-Path Build/ClientMain.dist/ClientMain.exe)){ exit 1 }
          Rename-Item Build/ClientMain.dist Client
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: Client/Build/
          dest: PYCM-Client-Windows.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Client-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}