name: Build Linux

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Console:
    runs-on: ubuntu-18.04
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Console
        run: |
          echo "BUILD_INFO = 'Linux v"${{ steps.tag.outputs.result }}" (64-bit)'" > BuildInfo.py
      - name: Build
        working-directory: Console
        run: |
          nuitka3 --standalone \
                  --include-data-file=Translation/*.qm=Translation/ \
                  --enable-plugin=pyqt5 --enable-plugin=multiprocessing \
                  --assume-yes-for-downloads --disable-ccache --remove-output \
                  --output-dir=Build ConsoleMain.py
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: Console/Build/
          dest: PYCM-Console-Linux.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Console-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-Client:
    runs-on: ubuntu-18.04
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Client
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.result }}
        run: |
          echo "BUILD_INFO = 'Linux v"${{ steps.tag.outputs.result }}" (64-bit)'" > BuildInfo.py
      - name: Build
        working-directory: Client
        run: |
          nuitka3 --standalone \
                  --include-data-file=Translation/*.qm=Translation/ \
                  --enable-plugin=pyqt5 \
                  --assume-yes-for-downloads --disable-ccache --remove-output \
                  --output-dir=Build ClientMain.py
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: Client/Build/
          dest: PYCM-Client-Linux.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Client-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}